export const ROLES = Object.freeze({
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  SALESPERSON: 'SALESPERSON',
});

export const ROLE_VALUES = Object.values(ROLES);

export const INVENTORY_TRANSACTION_TYPES = Object.freeze({
  OPENING_STOCK: 'OPENING_STOCK',
  STOCK_RECEIPT: 'STOCK_RECEIPT',
  SALE: 'SALE',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  DAMAGE: 'DAMAGE',
  SHORTAGE: 'SHORTAGE',
  SURPLUS: 'SURPLUS',
  ADJUSTMENT: 'ADJUSTMENT',
  REVERSAL: 'REVERSAL',
});

export const INVENTORY_TRANSACTION_TYPE_VALUES = Object.values(INVENTORY_TRANSACTION_TYPES);

export const INVENTORY_DIRECTIONS = Object.freeze({
  IN: 'IN',
  OUT: 'OUT',
});

export const INVENTORY_DIRECTION_VALUES = Object.values(INVENTORY_DIRECTIONS);

export const INVENTORY_TRANSACTION_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  VOIDED: 'VOIDED',
});

export const INVENTORY_TRANSACTION_STATUS_VALUES = Object.values(INVENTORY_TRANSACTION_STATUSES);

export const REFERENCE_TYPES = Object.freeze({
  OPENING_STOCK: 'OPENING_STOCK',
  STOCK_RECEIPT: 'STOCK_RECEIPT',
  DAILY_SALES_REPORT: 'DAILY_SALES_REPORT',
  SALE_ORDER: 'SALE_ORDER',
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  TRANSFER: 'TRANSFER',
  RECONCILIATION: 'RECONCILIATION',
  MANUAL: 'MANUAL',
});

export const REFERENCE_TYPE_VALUES = Object.values(REFERENCE_TYPES);

export const STOCK_RECEIPT_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

export const STOCK_RECEIPT_STATUS_VALUES = Object.values(STOCK_RECEIPT_STATUSES);

export const AUDIT_ACTIONS = Object.freeze({
  OPENING_STOCK_CREATED: 'OPENING_STOCK_CREATED',
  STOCK_RECEIPT_SUBMITTED: 'STOCK_RECEIPT_SUBMITTED',
  STOCK_RECEIPT_APPROVED: 'STOCK_RECEIPT_APPROVED',
  STOCK_RECEIPT_REJECTED: 'STOCK_RECEIPT_REJECTED',
  DAILY_SALES_REPORT_SUBMITTED: 'DAILY_SALES_REPORT_SUBMITTED',
});

// A DailySalesReport is immutable once submitted in Phase 3 — this single
// status exists so a future reversal/correction workflow has somewhere to
// record a different state without a schema change.
export const DAILY_SALES_REPORT_STATUSES = Object.freeze({
  SUBMITTED: 'SUBMITTED',
});

export const DAILY_SALES_REPORT_STATUS_VALUES = Object.values(DAILY_SALES_REPORT_STATUSES);
